import type { Dsr, DsrSubmitter, ReceivedDsr } from "./dsr.types";

export const projects: string[] = [
    "N-A",
    "Portal Redesign",
    "API Gateway",
    "Mobile App v2",
    "Data Pipeline",
    "Auth Service",
    "Analytics Dashboard",
    "Infra Migration",
];

export const ccOptions: string[] = [
    "manager@dsr.com",
    "hr@dsr.com",
    "team-lead@dsr.com",
    "pm@dsr.com",
];

export const teamMembers: DsrSubmitter[] = [
    {
        id: "s1",
        name: "Priya Sharma",
        email: "priya@dsr.com",
        avatar: "PS",
        department: "Engineering",
    },
    {
        id: "s2",
        name: "Rahul Verma",
        email: "rahul@dsr.com",
        avatar: "RV",
        department: "Engineering",
    },
    { id: "s3", name: "Ananya Patel", email: "ananya@dsr.com", avatar: "AP", department: "Design" },
    { id: "s4", name: "Vikram Singh", email: "vikram@dsr.com", avatar: "VS", department: "Design" },
    { id: "s5", name: "Neha Gupta", email: "neha@dsr.com", avatar: "NG", department: "Marketing" },
    { id: "s6", name: "Arjun Nair", email: "arjun@dsr.com", avatar: "AN", department: "Finance" },
];

export const mockSentDsrs: Dsr[] = [
    {
        id: "dsr-001",
        date: "2026-07-30",
        status: "Pending",
        entries: [
            {
                id: "e1",
                projectName: "Portal Redesign",
                description:
                    "Worked on the sidebar refactor and navigation component. Updated the collapsible menu items.",
                startTime: "09:00",
                endTime: "10:30",
                timeEstimate: "1 Hr 30 Min",
            },
            {
                id: "e2",
                projectName: "API Gateway",
                description:
                    "Fixed rate limiting bug in the gateway middleware. Added tests for edge cases.",
                startTime: "10:30",
                endTime: "13:00",
                timeEstimate: "2 Hr 30 Min",
            },
            {
                id: "e3",
                projectName: "N-A",
                description: "Team standup and sprint planning meeting.",
                startTime: "14:00",
                endTime: "15:00",
                timeEstimate: "1 Hr",
            },
            {
                id: "e4",
                projectName: "Portal Redesign",
                description: "Code review for PR #234 and #235. Reviewed auth module changes.",
                startTime: "15:00",
                endTime: "17:00",
                timeEstimate: "2 Hr",
            },
        ],
        sendTo: ["manager@dsr.com", "team-lead@dsr.com"],
        ccTo: ["hr@dsr.com"],
        attachments: ["screenshot-dashboard.png"],
    },
    {
        id: "dsr-002",
        date: "2026-07-29",
        status: "Approved",
        entries: [
            {
                id: "e5",
                projectName: "Mobile App v2",
                description: "Implemented push notification service for iOS and Android.",
                startTime: "09:00",
                endTime: "12:00",
                timeEstimate: "3 Hr",
            },
            {
                id: "e6",
                projectName: "Mobile App v2",
                description: "Fixed deep linking issues on Android 14.",
                startTime: "13:00",
                endTime: "16:00",
                timeEstimate: "3 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: [],
        attachments: [],
    },
    {
        id: "dsr-003",
        date: "2026-07-28",
        status: "Rejected",
        rejectionReason:
            "Please add more detail to the API Gateway entry — time estimate seems too high for the described work.",
        entries: [
            {
                id: "e7",
                projectName: "API Gateway",
                description: "Worked on gateway configuration.",
                startTime: "09:00",
                endTime: "17:00",
                timeEstimate: "8 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: [],
        attachments: [],
    },
    {
        id: "dsr-004",
        date: "2026-07-27",
        status: "Approved",
        entries: [
            {
                id: "e8",
                projectName: "Data Pipeline",
                description: "Optimized ETL job performance by 40%. Reduced memory footprint.",
                startTime: "09:00",
                endTime: "11:30",
                timeEstimate: "2 Hr 30 Min",
            },
            {
                id: "e9",
                projectName: "Auth Service",
                description: "Added OAuth2 PKCE flow for mobile clients.",
                startTime: "11:30",
                endTime: "15:00",
                timeEstimate: "3 Hr 30 Min",
            },
            {
                id: "e10",
                projectName: "N-A",
                description: "Sprint retrospective and planning.",
                startTime: "15:00",
                endTime: "17:00",
                timeEstimate: "2 Hr",
            },
        ],
        sendTo: ["manager@dsr.com", "pm@dsr.com"],
        ccTo: ["team-lead@dsr.com", "hr@dsr.com"],
        attachments: ["pipeline-metrics.pdf"],
    },
    {
        id: "dsr-005",
        date: "2026-07-26",
        status: "Pending",
        entries: [
            {
                id: "e11",
                projectName: "Analytics Dashboard",
                description: "Designed new chart components for user engagement metrics.",
                startTime: "09:00",
                endTime: "12:00",
                timeEstimate: "3 Hr",
            },
            {
                id: "e12",
                projectName: "Analytics Dashboard",
                description: "Integrated real-time data streaming via WebSockets.",
                startTime: "13:00",
                endTime: "17:30",
                timeEstimate: "4 Hr 30 Min",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: ["pm@dsr.com"],
        attachments: ["mockup-v2.fig"],
    },
    {
        id: "dsr-006",
        date: "2026-07-25",
        status: "Approved",
        entries: [
            {
                id: "e13",
                projectName: "Infra Migration",
                description: "Migrated 3 microservices from EC2 to ECS Fargate.",
                startTime: "09:00",
                endTime: "14:00",
                timeEstimate: "5 Hr",
            },
            {
                id: "e14",
                projectName: "N-A",
                description: "On-call handover and documentation update.",
                startTime: "14:00",
                endTime: "15:00",
                timeEstimate: "1 Hr",
            },
        ],
        sendTo: ["manager@dsr.com", "team-lead@dsr.com"],
        ccTo: [],
        attachments: ["migration-report.md"],
    },
    {
        id: "dsr-007",
        date: "2026-07-24",
        status: "Pending",
        entries: [
            {
                id: "e15",
                projectName: "Portal Redesign",
                description: "Refactored CSS variables and design tokens for the new theme system.",
                startTime: "09:00",
                endTime: "12:30",
                timeEstimate: "3 Hr 30 Min",
            },
            {
                id: "e16",
                projectName: "API Gateway",
                description: "Implemented request validation middleware.",
                startTime: "13:30",
                endTime: "17:00",
                timeEstimate: "3 Hr 30 Min",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: ["team-lead@dsr.com"],
        attachments: [],
    },
    {
        id: "dsr-008",
        date: "2026-07-23",
        status: "Rejected",
        rejectionReason:
            "Entries are too vague. Break down the 'various tasks' into specific items with time estimates.",
        entries: [
            {
                id: "e17",
                projectName: "N-A",
                description: "Various tasks and meetings throughout the day.",
                startTime: "09:00",
                endTime: "17:00",
                timeEstimate: "8 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: [],
        attachments: [],
    },
];

export const mockReceivedDsrs: ReceivedDsr[] = [
    {
        id: "rdsr-001",
        date: "2026-07-30",
        status: "Pending",
        entries: [
            {
                id: "re1",
                projectName: "Portal Redesign",
                description: "Updated color tokens for dark mode support across all components.",
                startTime: "09:00",
                endTime: "11:00",
                timeEstimate: "2 Hr",
            },
            {
                id: "re2",
                projectName: "Mobile App v2",
                description: "Fixed layout issues on tablet breakpoints for the settings screen.",
                startTime: "11:00",
                endTime: "14:00",
                timeEstimate: "3 Hr",
            },
            {
                id: "re3",
                projectName: "N-A",
                description: "Design review with the product team.",
                startTime: "14:30",
                endTime: "15:30",
                timeEstimate: "1 Hr",
            },
        ],
        sendTo: ["manager@dsr.com", "design-lead@dsr.com"],
        ccTo: [],
        attachments: ["dark-mode-preview.png"],
        submittedBy: {
            id: "s3",
            name: "Ananya Patel",
            email: "ananya@dsr.com",
            avatar: "AP",
            department: "Design",
        },
        sharedAt: "2026-07-30T17:30:00Z",
    },
    {
        id: "rdsr-002",
        date: "2026-07-29",
        status: "Pending",
        entries: [
            {
                id: "re4",
                projectName: "Portal Redesign",
                description: "Created new icon set for the sidebar navigation. Exported SVGs.",
                startTime: "09:00",
                endTime: "12:00",
                timeEstimate: "3 Hr",
            },
            {
                id: "re5",
                projectName: "Portal Redesign",
                description: "Designed empty states for all list views.",
                startTime: "13:00",
                endTime: "16:00",
                timeEstimate: "3 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: ["design-lead@dsr.com"],
        attachments: ["icons.zip", "empty-states.fig"],
        submittedBy: {
            id: "s3",
            name: "Ananya Patel",
            email: "ananya@dsr.com",
            avatar: "AP",
            department: "Design",
        },
        sharedAt: "2026-07-29T17:00:00Z",
    },
    {
        id: "rdsr-003",
        date: "2026-07-28",
        status: "Approved",
        entries: [
            {
                id: "re6",
                projectName: "Mobile App v2",
                description: "Redesigned the onboarding flow with 3 new screens.",
                startTime: "09:00",
                endTime: "13:00",
                timeEstimate: "4 Hr",
            },
            {
                id: "re7",
                projectName: "N-A",
                description: "Usability testing session with 5 participants.",
                startTime: "14:00",
                endTime: "16:00",
                timeEstimate: "2 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: [],
        attachments: ["onboarding-flow.pdf"],
        submittedBy: {
            id: "s3",
            name: "Ananya Patel",
            email: "ananya@dsr.com",
            avatar: "AP",
            department: "Design",
        },
        sharedAt: "2026-07-28T16:30:00Z",
    },
    {
        id: "rdsr-004",
        date: "2026-07-30",
        status: "Pending",
        entries: [
            {
                id: "re8",
                projectName: "API Gateway",
                description:
                    "Load tested the gateway with 10k concurrent connections. Identified bottleneck in auth middleware.",
                startTime: "09:00",
                endTime: "12:00",
                timeEstimate: "3 Hr",
            },
            {
                id: "re9",
                projectName: "API Gateway",
                description: "Optimized JWT verification cache. Reduced p99 latency by 35%.",
                startTime: "13:00",
                endTime: "16:00",
                timeEstimate: "3 Hr",
            },
            {
                id: "re10",
                projectName: "N-A",
                description: "Documented load testing results and shared with infra team.",
                startTime: "16:00",
                endTime: "17:00",
                timeEstimate: "1 Hr",
            },
        ],
        sendTo: ["manager@dsr.com", "team-lead@dsr.com"],
        ccTo: ["infra@dsr.com"],
        attachments: ["load-test-report.pdf"],
        submittedBy: {
            id: "s1",
            name: "Priya Sharma",
            email: "priya@dsr.com",
            avatar: "PS",
            department: "Engineering",
        },
        sharedAt: "2026-07-30T17:15:00Z",
    },
    {
        id: "rdsr-005",
        date: "2026-07-29",
        status: "Approved",
        entries: [
            {
                id: "re11",
                projectName: "Data Pipeline",
                description: "Built new data ingestion connector for Salesforce API.",
                startTime: "09:00",
                endTime: "13:00",
                timeEstimate: "4 Hr",
            },
            {
                id: "re12",
                projectName: "Data Pipeline",
                description:
                    "Added data validation rules and error handling for malformed records.",
                startTime: "14:00",
                endTime: "17:00",
                timeEstimate: "3 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: ["data-team@dsr.com"],
        attachments: [],
        submittedBy: {
            id: "s1",
            name: "Priya Sharma",
            email: "priya@dsr.com",
            avatar: "PS",
            department: "Engineering",
        },
        sharedAt: "2026-07-29T17:30:00Z",
    },
    {
        id: "rdsr-006",
        date: "2026-07-28",
        status: "Rejected",
        rejectionReason:
            "The Data Pipeline entry lacks specific metrics. How many records processed? What was the error rate?",
        entries: [
            {
                id: "re13",
                projectName: "Data Pipeline",
                description: "Worked on data pipeline improvements and bug fixes.",
                startTime: "09:00",
                endTime: "17:00",
                timeEstimate: "8 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: [],
        attachments: [],
        submittedBy: {
            id: "s1",
            name: "Priya Sharma",
            email: "priya@dsr.com",
            avatar: "PS",
            department: "Engineering",
        },
        sharedAt: "2026-07-28T17:00:00Z",
    },
    {
        id: "rdsr-007",
        date: "2026-07-30",
        status: "Pending",
        entries: [
            {
                id: "re14",
                projectName: "Analytics Dashboard",
                description: "Wrote campaign performance report automation script.",
                startTime: "09:00",
                endTime: "11:30",
                timeEstimate: "2 Hr 30 Min",
            },
            {
                id: "re15",
                projectName: "Analytics Dashboard",
                description: "Prepared Q3 marketing metrics presentation for leadership.",
                startTime: "13:00",
                endTime: "17:00",
                timeEstimate: "4 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: ["marketing-lead@dsr.com"],
        attachments: ["q3-metrics.pptx"],
        submittedBy: {
            id: "s5",
            name: "Neha Gupta",
            email: "neha@dsr.com",
            avatar: "NG",
            department: "Marketing",
        },
        sharedAt: "2026-07-30T17:20:00Z",
    },
    {
        id: "rdsr-008",
        date: "2026-07-29",
        status: "Approved",
        entries: [
            {
                id: "re16",
                projectName: "Analytics Dashboard",
                description: "Set up A/B test tracking for the new landing page variants.",
                startTime: "09:00",
                endTime: "12:00",
                timeEstimate: "3 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: [],
        attachments: [],
        submittedBy: {
            id: "s5",
            name: "Neha Gupta",
            email: "neha@dsr.com",
            avatar: "NG",
            department: "Marketing",
        },
        sharedAt: "2026-07-29T14:00:00Z",
    },
    {
        id: "rdsr-009",
        date: "2026-07-30",
        status: "Pending",
        entries: [
            {
                id: "re17",
                projectName: "Infra Migration",
                description: "Set up Terraform modules for the new staging environment.",
                startTime: "09:00",
                endTime: "12:30",
                timeEstimate: "3 Hr 30 Min",
            },
            {
                id: "re18",
                projectName: "Infra Migration",
                description: "Configured monitoring alerts and dashboards in Grafana.",
                startTime: "13:30",
                endTime: "17:00",
                timeEstimate: "3 Hr 30 Min",
            },
        ],
        sendTo: ["manager@dsr.com", "team-lead@dsr.com"],
        ccTo: ["devops@dsr.com"],
        attachments: ["terraform-plan.txt"],
        submittedBy: {
            id: "s2",
            name: "Rahul Verma",
            email: "rahul@dsr.com",
            avatar: "RV",
            department: "Engineering",
        },
        sharedAt: "2026-07-30T17:45:00Z",
    },
    {
        id: "rdsr-010",
        date: "2026-07-28",
        status: "Pending",
        entries: [
            {
                id: "re19",
                projectName: "Auth Service",
                description: "Implemented SSO integration with Okta for enterprise customers.",
                startTime: "09:00",
                endTime: "13:00",
                timeEstimate: "4 Hr",
            },
            {
                id: "re20",
                projectName: "Auth Service",
                description: "Wrote integration tests for the SSO flow. All passing.",
                startTime: "14:00",
                endTime: "17:00",
                timeEstimate: "3 Hr",
            },
        ],
        sendTo: ["manager@dsr.com"],
        ccTo: ["security@dsr.com"],
        attachments: [],
        submittedBy: {
            id: "s2",
            name: "Rahul Verma",
            email: "rahul@dsr.com",
            avatar: "RV",
            department: "Engineering",
        },
        sharedAt: "2026-07-28T17:30:00Z",
    },
];

export const today = new Date().toISOString().split("T")[0];
