/** Dummy data local to the dashboard module. Extract to src/data/ only when shared across modules. */

import type {
    ActivityItem,
    AttendanceDay,
    Department,
    Employee,
    LeaveRequest,
} from "./dashboard.types";

export const departments: Department[] = ["Engineering", "Design", "HR", "Marketing", "Finance"];

export const employees: Employee[] = [
    {
        id: "1",
        name: "Priya Sharma",
        email: "priya@dsr.com",
        department: "Engineering",
        status: "Present",
        checkInTime: "09:02 AM",
        avatar: "PS",
    },
    {
        id: "2",
        name: "Rahul Verma",
        email: "rahul@dsr.com",
        department: "Engineering",
        status: "Present",
        checkInTime: "09:15 AM",
        avatar: "RV",
    },
    {
        id: "3",
        name: "Ananya Patel",
        email: "ananya@dsr.com",
        department: "Engineering",
        status: "Present",
        checkInTime: "08:58 AM",
        avatar: "AP",
    },
    {
        id: "4",
        name: "Vikram Singh",
        email: "vikram@dsr.com",
        department: "Engineering",
        status: "On Leave",
        checkInTime: null,
        avatar: "VS",
    },
    {
        id: "5",
        name: "Neha Gupta",
        email: "neha@dsr.com",
        department: "Engineering",
        status: "Present",
        checkInTime: "09:30 AM",
        avatar: "NG",
    },
    {
        id: "6",
        name: "Arjun Nair",
        email: "arjun@dsr.com",
        department: "Design",
        status: "Present",
        checkInTime: "09:05 AM",
        avatar: "AN",
    },
    {
        id: "7",
        name: "Meera Joshi",
        email: "meera@dsr.com",
        department: "Design",
        status: "Present",
        checkInTime: "09:20 AM",
        avatar: "MJ",
    },
    {
        id: "8",
        name: "Karan Malhotra",
        email: "karan@dsr.com",
        department: "Design",
        status: "Absent",
        checkInTime: null,
        avatar: "KM",
    },
    {
        id: "9",
        name: "Divya Reddy",
        email: "divya@dsr.com",
        department: "Design",
        status: "Present",
        checkInTime: "09:12 AM",
        avatar: "DR",
    },
    {
        id: "10",
        name: "Suresh Kumar",
        email: "suresh@dsr.com",
        department: "HR",
        status: "Present",
        checkInTime: "08:50 AM",
        avatar: "SK",
    },
    {
        id: "11",
        name: "Lakshmi Iyer",
        email: "lakshmi@dsr.com",
        department: "HR",
        status: "Present",
        checkInTime: "09:02 AM",
        avatar: "LI",
    },
    {
        id: "12",
        name: "Rajesh Tiwari",
        email: "rajesh@dsr.com",
        department: "HR",
        status: "On Leave",
        checkInTime: null,
        avatar: "RT",
    },
    {
        id: "13",
        name: "Pooja Agarwal",
        email: "pooja@dsr.com",
        department: "Marketing",
        status: "Present",
        checkInTime: "09:18 AM",
        avatar: "PA",
    },
    {
        id: "14",
        name: "Amit Das",
        email: "amit@dsr.com",
        department: "Marketing",
        status: "Present",
        checkInTime: "09:25 AM",
        avatar: "AD",
    },
    {
        id: "15",
        name: "Sunita Rao",
        email: "sunita@dsr.com",
        department: "Marketing",
        status: "Present",
        checkInTime: "08:55 AM",
        avatar: "SR",
    },
    {
        id: "16",
        name: "Rohan Mehta",
        email: "rohan@dsr.com",
        department: "Marketing",
        status: "Absent",
        checkInTime: null,
        avatar: "RM",
    },
    {
        id: "17",
        name: "Kavita Shah",
        email: "kavita@dsr.com",
        department: "Marketing",
        status: "On Leave",
        checkInTime: null,
        avatar: "KS",
    },
    {
        id: "18",
        name: "Deepak Chandra",
        email: "deepak@dsr.com",
        department: "Finance",
        status: "Present",
        checkInTime: "09:10 AM",
        avatar: "DC",
    },
    {
        id: "19",
        name: "Ritu Kapoor",
        email: "ritu@dsr.com",
        department: "Finance",
        status: "Present",
        checkInTime: "09:00 AM",
        avatar: "RK",
    },
    {
        id: "20",
        name: "Mohit Bansal",
        email: "mohit@dsr.com",
        department: "Finance",
        status: "Present",
        checkInTime: "09:22 AM",
        avatar: "MB",
    },
    {
        id: "21",
        name: "Sneha Pillai",
        email: "sneha@dsr.com",
        department: "Finance",
        status: "On Leave",
        checkInTime: null,
        avatar: "SP",
    },
    {
        id: "22",
        name: "Vivek Anand",
        email: "vivek@dsr.com",
        department: "Engineering",
        status: "Absent",
        checkInTime: null,
        avatar: "VA",
    },
    {
        id: "23",
        name: "Charu Desai",
        email: "charu@dsr.com",
        department: "HR",
        status: "Present",
        checkInTime: "09:28 AM",
        avatar: "CD",
    },
    {
        id: "24",
        name: "Nitin Saxena",
        email: "nitin@dsr.com",
        department: "Finance",
        status: "Present",
        checkInTime: "08:48 AM",
        avatar: "NS",
    },
    {
        id: "25",
        name: "Anjali Thakur",
        email: "anjali@dsr.com",
        department: "Design",
        status: "Present",
        checkInTime: "09:14 AM",
        avatar: "AT",
    },
];

export const leaveRequests: LeaveRequest[] = [
    {
        id: "lr1",
        employeeName: "Vikram Singh",
        type: "Sick",
        from: "2026-07-29",
        to: "2026-07-30",
        status: "Pending",
    },
    {
        id: "lr2",
        employeeName: "Rajesh Tiwari",
        type: "Vacation",
        from: "2026-08-01",
        to: "2026-08-05",
        status: "Pending",
    },
    {
        id: "lr3",
        employeeName: "Kavita Shah",
        type: "Personal",
        from: "2026-07-28",
        to: "2026-07-29",
        status: "Approved",
    },
    {
        id: "lr4",
        employeeName: "Sneha Pillai",
        type: "Sick",
        from: "2026-07-29",
        to: "2026-07-31",
        status: "Pending",
    },
    {
        id: "lr5",
        employeeName: "Arjun Nair",
        type: "Vacation",
        from: "2026-08-10",
        to: "2026-08-14",
        status: "Pending",
    },
    {
        id: "lr6",
        employeeName: "Divya Reddy",
        type: "Personal",
        from: "2026-08-03",
        to: "2026-08-03",
        status: "Pending",
    },
];

export const attendanceTrend: AttendanceDay[] = [
    { day: "Mon", present: 22, total: 25 },
    { day: "Tue", present: 23, total: 25 },
    { day: "Wed", present: 20, total: 25 },
    { day: "Thu", present: 24, total: 25 },
    { day: "Fri", present: 21, total: 25 },
    { day: "Sat", present: 15, total: 20 },
    { day: "Sun", present: 12, total: 18 },
];

export const recentActivity: ActivityItem[] = [
    {
        id: "a1",
        employeeName: "Priya Sharma",
        action: "checked in",
        timestamp: "10 minutes ago",
        unread: true,
    },
    {
        id: "a2",
        employeeName: "Vikram Singh",
        action: "requested sick leave",
        timestamp: "25 minutes ago",
        unread: true,
    },
    {
        id: "a3",
        employeeName: "Neha Gupta",
        action: "submitted daily report",
        timestamp: "1 hour ago",
        unread: false,
    },
    {
        id: "a4",
        employeeName: "Karan Malhotra",
        action: "marked absent",
        timestamp: "2 hours ago",
        unread: true,
    },
    {
        id: "a5",
        employeeName: "Lakshmi Iyer",
        action: "updated department roster",
        timestamp: "3 hours ago",
        unread: false,
    },
    {
        id: "a6",
        employeeName: "Amit Das",
        action: "requested vacation",
        timestamp: "4 hours ago",
        unread: false,
    },
    {
        id: "a7",
        employeeName: "Ritu Kapoor",
        action: "checked in late",
        timestamp: "5 hours ago",
        unread: false,
    },
];

export const departmentCounts: Record<Department, number> = {
    Engineering: 6,
    Design: 5,
    HR: 4,
    Marketing: 5,
    Finance: 5,
};

export const stats = {
    total: employees.length,
    present: employees.filter((e) => e.status === "Present").length,
    absent: employees.filter((e) => e.status === "Absent").length,
    onLeave: employees.filter((e) => e.status === "On Leave").length,
    pendingRequests: leaveRequests.filter((r) => r.status === "Pending").length,
};
