/** Dummy data local to the DSR dashboard module. Extract to src/data/ only when shared across modules. */

import type {
    DsrEntry,
    DsrStats,
    DsrStatus,
    HoursSlice,
    StatItem,
} from "./dashboard.types";

export const dsrEntries: DsrEntry[] = [
    {
        id: "dsr-1",
        submittedBy: "Sunil Kumar",
        avatar: "SK",
        date: "2025-07-28",
        project: "Samwad App",
        ticket: "SAM-24",
        description: "Worked on the CCA certificate flow and fixed preview rendering issues.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-2",
        submittedBy: "Sunil Kumar",
        avatar: "SK",
        date: "2025-07-27",
        project: "Samwad App",
        ticket: "SAM-24",
        description: "Worked on the CCA form validation and inline error states.",
        status: "Pending",
        totalHours: 5,
    },
    {
        id: "dsr-3",
        submittedBy: "Ankit Verma",
        avatar: "AV",
        date: "2025-07-28",
        project: "DSR Portal",
        ticket: "DSR-12",
        description: "Implemented DSR listing API integration with server-side pagination.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-4",
        submittedBy: "Aashish Rana",
        avatar: "AR",
        date: "2025-07-28",
        project: "Samwad App",
        ticket: "SAM-31",
        description: "Fixed push notification token refresh when the app resumes.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-5",
        submittedBy: "Priya Sharma",
        avatar: "PS",
        date: "2025-07-28",
        project: "CCA Dashboard",
        ticket: "CCA-7",
        description: "Built hours distribution chart and connected weekly aggregates.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-6",
        submittedBy: "Rahul Meena",
        avatar: "RM",
        date: "2025-07-27",
        project: "HRMS Suite",
        ticket: "HRM-33",
        description: "Refactored leave approval workflow and notification email templates.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-7",
        submittedBy: "Kavya Nair",
        avatar: "KN",
        date: "2025-07-27",
        project: "DSR Portal",
        ticket: "DSR-18",
        description: "Added filter toolbar state handling for date and status fields.",
        status: "Pending",
        totalHours: 6,
    },
    {
        id: "dsr-8",
        submittedBy: "Rohit Shetty",
        avatar: "RS",
        date: "2025-07-27",
        project: "Orion CRM",
        ticket: "ORM-21",
        description: "Migrated contact import job to a background queue with retries.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-9",
        submittedBy: "Manish Gupta",
        avatar: "MG",
        date: "2025-07-26",
        project: "Fleet Tracker",
        ticket: "FLT-14",
        description: "Tuned GPS polling interval to reduce battery drain on devices.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-10",
        submittedBy: "Nidhi Shah",
        avatar: "NS",
        date: "2025-07-26",
        project: "CCA Dashboard",
        ticket: "CCA-9",
        description: "Designed empty and loading states for the report screens.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-11",
        submittedBy: "Arjun Desai",
        avatar: "AD",
        date: "2025-07-26",
        project: "DSR Portal",
        ticket: "DSR-12",
        description: "Wrote API contract tests for the DSR submission endpoint.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-12",
        submittedBy: "Sunil Kumar",
        avatar: "SK",
        date: "2025-07-26",
        project: "Samwad App",
        ticket: "SAM-25",
        description: "Investigated crash on attachment upload for large files.",
        status: "Pending",
        totalHours: 5,
    },
    {
        id: "dsr-13",
        submittedBy: "Ankit Verma",
        avatar: "AV",
        date: "2025-07-25",
        project: "Orion CRM",
        ticket: "ORM-24",
        description: "Built dedupe logic for bulk lead imports across sources.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-14",
        submittedBy: "Priya Sharma",
        avatar: "PS",
        date: "2025-07-25",
        project: "DSR Portal",
        ticket: "DSR-19",
        description: "Polished table density and pagination footer interactions.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-15",
        submittedBy: "Aashish Rana",
        avatar: "AR",
        date: "2025-07-25",
        project: "HRMS Suite",
        ticket: "HRM-35",
        description: "Added shift roster conflict warnings for schedulers.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-16",
        submittedBy: "Kavya Nair",
        avatar: "KN",
        date: "2025-07-25",
        project: "CCA Dashboard",
        ticket: "CCA-7",
        description: "Optimized aggregate queries with materialized views.",
        status: "Pending",
        totalHours: 9,
    },
    {
        id: "dsr-17",
        submittedBy: "Rahul Meena",
        avatar: "RM",
        date: "2025-07-25",
        project: "Fleet Tracker",
        ticket: "FLT-18",
        description: "Implemented geofence entry and exit alerts for vehicles.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-18",
        submittedBy: "Rohit Shetty",
        avatar: "RS",
        date: "2025-07-24",
        project: "DSR Portal",
        ticket: "DSR-21",
        description: "Fixed timezone handling in report date filters.",
        status: "Submitted",
        totalHours: 7,
    },
    {
        id: "dsr-19",
        submittedBy: "Manish Gupta",
        avatar: "MG",
        date: "2025-07-24",
        project: "Samwad App",
        ticket: "SAM-28",
        description: "Improved offline sync retry logic with exponential backoff.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-20",
        submittedBy: "Nidhi Shah",
        avatar: "NS",
        date: "2025-07-24",
        project: "Orion CRM",
        ticket: "ORM-21",
        description: "Redesigned pipeline board drag interactions for touch.",
        status: "Pending",
        totalHours: 8,
    },
    {
        id: "dsr-21",
        submittedBy: "Arjun Desai",
        avatar: "AD",
        date: "2025-07-24",
        project: "HRMS Suite",
        ticket: "HRM-38",
        description: "Added audit log entries for payroll edits and exports.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-22",
        submittedBy: "Sunil Kumar",
        avatar: "SK",
        date: "2025-07-23",
        project: "Samwad App",
        ticket: "SAM-24",
        description: "Worked on the CCA approval chain and reviewer notes.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-23",
        submittedBy: "Ankit Verma",
        avatar: "AV",
        date: "2025-07-23",
        project: "CCA Dashboard",
        ticket: "CCA-11",
        description: "Set up anomaly alerts for unusual hour entries.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-24",
        submittedBy: "Priya Sharma",
        avatar: "PS",
        date: "2025-07-23",
        project: "Fleet Tracker",
        ticket: "FLT-20",
        description: "Built driver scorecard weekly digest email.",
        status: "Submitted",
        totalHours: 8,
    },
    {
        id: "dsr-25",
        submittedBy: "Aashish Rana",
        avatar: "AR",
        date: "2025-07-23",
        project: "DSR Portal",
        ticket: "DSR-23",
        description: "Added bulk approve action for pending DSRs.",
        status: "Pending",
        totalHours: 9,
    },
    {
        id: "dsr-26",
        submittedBy: "Kavya Nair",
        avatar: "KN",
        date: "2025-07-22",
        project: "HRMS Suite",
        ticket: "HRM-40",
        description: "Streamlined onboarding checklist assignments for HR.",
        status: "Submitted",
        totalHours: 7,
    },
    {
        id: "dsr-27",
        submittedBy: "Rahul Meena",
        avatar: "RM",
        date: "2025-07-22",
        project: "Samwad App",
        ticket: "SAM-30",
        description: "Fixed chat attachment thumbnails on low-end devices.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-28",
        submittedBy: "Rohit Shetty",
        avatar: "RS",
        date: "2025-07-22",
        project: "Orion CRM",
        ticket: "ORM-27",
        description: "Added activity timeline to the deal detail view.",
        status: "Submitted",
        totalHours: 9,
    },
    {
        id: "dsr-29",
        submittedBy: "Manish Gupta",
        avatar: "MG",
        date: "2025-07-22",
        project: "CCA Dashboard",
        ticket: "CCA-9",
        description: "Improved export CSV formatting for finance review.",
        status: "Pending",
        totalHours: 6,
    },
    {
        id: "dsr-30",
        submittedBy: "Nidhi Shah",
        avatar: "NS",
        date: "2025-07-21",
        project: "DSR Portal",
        ticket: "DSR-25",
        description: "Drafted notification preferences screen and settings copy.",
        status: "Submitted",
        totalHours: 7,
    },
];

export const dsrStats: DsrStats = {
    totalEmployees: 30,
    totalProjects: 20,
    totalTickets: 40,
    totalHours: 240,
};

export const dateOptions = [...new Set(dsrEntries.map((e) => e.date))].sort().reverse();
export const employeeOptions = [...new Set(dsrEntries.map((e) => e.submittedBy))].sort();
export const projectOptions = [...new Set(dsrEntries.map((e) => e.project))].sort();
export const ticketOptions = [...new Set(dsrEntries.map((e) => e.ticket))].sort();
export const statusOptions: DsrStatus[] = ["Submitted", "Pending"];

export const statItems: StatItem[] = [
    {
        label: "Total Employees",
        value: dsrStats.totalEmployees,
        sub: "Submitting daily reports",
        icon: "users",
        color: "bg-indigo-500/10 text-indigo-600",
        delay: "delay-0",
    },
    {
        label: "Total Projects",
        value: dsrStats.totalProjects,
        sub: "Active this quarter",
        icon: "folder",
        color: "bg-sky-500/10 text-sky-600",
        delay: "delay-75",
    },
    {
        label: "Total Tickets",
        value: dsrStats.totalTickets,
        sub: "Tracked across projects",
        icon: "ticket",
        color: "bg-violet-500/10 text-violet-600",
        delay: "delay-150",
    },
    {
        label: "Total Hours",
        value: dsrStats.totalHours,
        sub: "Logged in this listing",
        icon: "clock",
        color: "bg-emerald-500/10 text-emerald-600",
        delay: "delay-225",
    },
];

const palette = ["#6366f1", "#0ea5e9", "#10b981", "#f59e0b", "#8b5cf6", "#f43f5e", "#94a3b8"];

function aggregateHours(entries: DsrEntry[], key: "project" | "submittedBy") {
    const totals = new Map<string, number>();
    for (const entry of entries) {
        totals.set(entry[key], (totals.get(entry[key]) ?? 0) + entry.totalHours);
    }
    return [...totals.entries()]
        .map(([label, hours]) => ({ label, hours }))
        .sort((a, b) => b.hours - a.hours);
}

export const hoursByProject: HoursSlice[] = aggregateHours(dsrEntries, "project").map(
    (slice, i) => ({ ...slice, color: palette[i] }),
);

const employeeTotals = aggregateHours(dsrEntries, "submittedBy");
const otherHours = employeeTotals.slice(5).reduce((sum, s) => sum + s.hours, 0);

export const hoursByEmployee: HoursSlice[] = [
    ...employeeTotals.slice(0, 5).map((slice, i) => ({ ...slice, color: palette[i] })),
    { label: "Others", hours: otherHours, color: palette[6] },
];

export const navItems = [{ label: "DSR Listing", href: "/dashboard", active: true }];

export function formatDsrDate(iso: string): string {
    const [year, month, day] = iso.split("-");
    return `${month}/${day}/${year}`;
}
