export interface DevopsTicket {
    id: string;
    srNo: string;
    empCode: string;
    empName: string;
    ticketNo: string;
    ticketTitle: string;
    project: string;
    severity: string;
    createdDate: string;
    status: string;
    assigned: string;
}

export const DEVOPS_TICKET_PROJECTS = [
    "Select Project",
    "2 percent Realty (esign)",
    "528 Prep LMS",
    "Accost Global",
    "Adaptive Learning",
    "Aimsight",
    "Ammunition Cargo Management and Tracking",
    "APlus",
    "Apuls",
    "ATS",
    "Authconn",
    "Auto Hound",
    "Bamble",
    "BCM",
    "Bigtoe",
    "Biometric",
    "Blocktag",
    "Brand-Slice",
    "Bravvox",
    "BRD",
    "Bring Me",
    "BrothWork",
    "Brothworks",
    "Business Exchange",
    "Canasta Invoicing",
    "Canonizer",
    "Cardify Internal Project",
    "Caringhub",
    "Casey",
    "CDM",
    "CFM - Client Fund Managment",
    "Charaka",
    "Chatbot Plugin",
    "Cheer Points",
    "chesomachinary",
    "ChessStudentTracker",
    "City Link",
    "Clarity on Credit",
    "CoHelp",
    "Coradix",
    "Corkrules",
    "Covermy Insurance",
    "CRWD",
    "Customer Stack",
    "Cxo Web Mailer",
    "Dataorganizer",
    "Delish Deliveries",
    "DrinkUp",
    "DSR Manager",
    "Durugs@FDA",
    "EBS Live",
    "EBSLive",
    "eDinnar",
    "ElaraTech",
    "Email forworder",
    "Empiraa",
    "Employee Monitoring(Mertos)",
    "ePanic Button",
    "Ethnimetrics",
    "Eventsfy",
    "Eventsfy SEO",
    "Evercap",
    "Filterable Directory MVP",
    "FitFam",
    "Fleetsu",
    "Flexcheck Auto",
    "Food Matrix",
    "Foodbank",
    "Fuloop",
    "GelatoTrip/Desti",
    "Giveer",
    "Go Farm Yourself",
    "Green AIsle",
    "HealthFulAI",
    "Housepact",
    "Housiko",
    "Hypi",
    "Image Reko",
    "improve IPS",
    "INHAABIT",
    "ITM",
    "Itryte",
    "Jesus Live",
    "Knowledgestrap",
    "KW Services",
    "Landcarer",
    "Lead Scouters",
    "LearnYourWay",
    "LedSaves",
    "Lexandria.ai",
    "LnFound",
    "LookAfteryourdog",
    "Marketfloor",
    "MAUI",
    "Meeting Science",
    "MindWorks",
    "Minearc",
    "Momenta Boutique",
    "Mouldflow",
    "Muzepit",
    "My Rent Rewards",
    "MyBizzHive",
    "Newmde",
    "Nft_insights",
    "Notion Addon",
    "Ojolie",
    "One Fine Flat",
    "Oneday",
    "OneFantastic",
    "OneStudio OTT",
    "OptionsPlay",
    "OSQO",
    "Panancea Finder",
    "Partner Pulse",
    "Passionfruut",
    "Peace Building",
    "Photospace App",
    "Physics Concepts",
    "Pickaform",
    "Piqosity",
    "Places profile",
    "Productfolio",
    "Promarsal",
    "Prosmarketplace",
    "Rajeev Project",
    "RealtyPulsePro",
    "RecruitEasePro",
    "Royal Insurance",
    "RVIZ",
    "Sandro",
    "SaymDay",
    "Scanflip",
    "Scanflip",
    "Scholarbees",
    "Scoreahead",
    "Sea life rescue",
    "Settlebox",
    "Simplicity",
    "SIPBN",
    "Smart Ai Automation",
    "smart-habits",
    "SMS",
    "Soiled my Plants",
    "Soren Logistics",
    "Sports Marketplace",
    "Stocks with congress",
    "SYNTAQ (Andreyev Lawyer)",
    "Syntaq (Falcon)",
    "Taka Solutions",
    "Talent Hire",
    "Talentelgia Website",
    "Talentelgia.com Website",
    "TalentHire Mobile App",
    "TalentOne",
    "Teakalog",
    "TekaDash",
    "TEKaGUI",
    "TEKaHelp",
    "TekaLog",
    "TEKaPick",
    "TEKaVerse",
    "Theranostics",
    "Theranostics - DNA Management system",
    "Ticket Tracer and Blinkay Suite",
    "TMO",
    "TMOMobile App",
    "TMU",
    "Top10ReviewList",
    "Trades echo(Mobile App)",
    "TradesEcho",
    "Treat Umbraco",
    "Vallet parking App",
    "Version 47",
    "ViTutors",
    "Vrutti.AI",
    "Waterstation",
    "WunderMind",
];

export const DEVOPS_TICKET_SEVERITIES = ["All", "High", "Medium", "Low"];
export const DEVOPS_TICKET_STATUSES = [
    "All",
    "Open",
    "InProgress",
    "On Hold",
    "Resolved",
    "Closed",
    "Reopen",
    "Archive",
];
